language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mzhao/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mzhao/docker-react yarn test

deploy:
    provider: elasticbeanstalk
    region: "ca-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ca-central-1-375971864783"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

