language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t yong9900/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yong9900/docker-react npm run test
  

